cmake_minimum_required(VERSION 3.24)
if(NOT DEFINED ROOT)
  message(FATAL_ERROR "Pass -DROOT=<unpacked install tree>")
endif()
file(REAL_PATH "${ROOT}" ROOT)
set(ENV{QT_QPA_PLATFORM} offscreen)

if(EXISTS "${ROOT}/usr/bin")
  set(_bindir "${ROOT}/usr/bin")
else()
  set(_bindir "${ROOT}/bin")
endif()
if(CMAKE_HOST_WIN32)
  set(_suffix ".exe")
else()
  set(_suffix "")
endif()

function(run_checked exe)
  execute_process(COMMAND "${exe}" ${ARGN} RESULT_VARIABLE rc
                  OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 20)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "${exe} ${ARGN} failed (${rc})\n${out}\n${err}")
  endif()
endfunction()

run_checked("${_bindir}/mver-cli${_suffix}" --help)

# Exercise the real widget hierarchy and paint path, not merely QApplication
# startup. The PNG is retained with CI artifacts for visual inspection.
set(_gui_screenshot "${ROOT}/mver-gui-smoke.png")
file(REMOVE "${_gui_screenshot}")
run_checked("${_bindir}/mver${_suffix}" --screenshot "${_gui_screenshot}")
if(NOT EXISTS "${_gui_screenshot}")
  message(FATAL_ERROR "GUI smoke test did not create ${_gui_screenshot}")
endif()
file(READ "${_gui_screenshot}" _png_magic HEX OFFSET 0 LIMIT 8)
if(NOT _png_magic STREQUAL "89504e470d0a1a0a")
  message(FATAL_ERROR "GUI smoke output is not a valid PNG: ${_gui_screenshot}")
endif()

if(CMAKE_HOST_WIN32)
  find_program(DUMPBIN dumpbin REQUIRED)
  foreach(exe mver mver-cli)
    execute_process(COMMAND "${DUMPBIN}" /dependents "${_bindir}/${exe}.exe"
                    OUTPUT_VARIABLE deps COMMAND_ERROR_IS_FATAL ANY)
    if(deps MATCHES "[.]conan2|[/\\\\](build|_build)[/\\\\]")
      message(FATAL_ERROR "${exe} references a build/Conan path:\n${deps}")
    endif()
  endforeach()
else()
  foreach(exe mver mver-cli)
    execute_process(
      COMMAND sh -c "LD_DEBUG=libs \"$1\" --help 2>&1" sh "${_bindir}/${exe}"
      OUTPUT_VARIABLE loaded ERROR_VARIABLE loaded_error RESULT_VARIABLE loaded_rc)
    string(APPEND loaded "\n${loaded_error}")
    if(NOT loaded_rc EQUAL 0)
      message(FATAL_ERROR "Loader audit failed for ${exe} (${loaded_rc}):\n${loaded}")
    endif()
    if(loaded MATCHES "[.]conan2|[/](build|_build)[/]")
      message(FATAL_ERROR "${exe} loaded a build/Conan library:\n${loaded}")
    endif()
    execute_process(COMMAND readelf -d "${_bindir}/${exe}" OUTPUT_VARIABLE elf COMMAND_ERROR_IS_FATAL ANY)
    if(elf MATCHES "(RPATH|RUNPATH).*(/home/|[.]conan2|/(build|_build)/)")
      message(FATAL_ERROR "${exe} has a non-relocatable RPATH:\n${elf}")
    endif()
  endforeach()
endif()
